---
global:
  dnsService: coredns
loki:
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  limits_config:
    retention_period: 168h
  ingester:
    chunk_encoding: snappy
  compactor:
    working_directory: /data/retention
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
    delete_request_store: s3
  tracing:
    enabled: true
  querier:
    max_concurrent: 4
gateway:
  verboseLogging: false
  service:
    # -- Port of the gateway service
    port: 80
    # -- Type of the gateway service
    type: NodePort
    # -- ClusterIP of the gateway service
    clusterIP: null
    # -- (int) Node port if service type is NodePort
    nodePort: 31080
    # -- Load balancer IPO address if service type is LoadBalancer
    loadBalancerIP: null
    # -- Annotations for the gateway service
    annotations: {}
    # -- Labels for gateway service
    labels: {}
deploymentMode: SimpleScalable
backend:
  affinity: {}
  replicas: 2
  extraArgs:
    - -log.level=warn
  extraVolumeMounts:
    - name: compactor
      mountPath: /data/retention
  extraVolumes:
    - name: compactor
      emptyDir: {}
read:
  affinity: {}
  replicas: 2
  extraArgs:
    - -querier.multi-tenant-queries-enabled=true
    - -log.level=warn
write:
  affinity: {}
  replicas: 2
  extraArgs:
    - -log.level=warn
minio:
  enabled: true
  persistence:
    size: 20Gi
singleBinary:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
