apiVersion: v1
kind: Secret
metadata:
  name: vector-agent-events-sink-loki
  namespace: kubesphere-logging-system
  labels:
    logging.whizard.io/component: "events"
    logging.whizard.io/vector-role: Agent
    logging.whizard.io/enable: "true"
stringData:
  sink.yaml: |
    sinks:
      loki-events:
        type: loki
        inputs:
        - kube_events_remapped
        endpoint: http://loki-gateway.loki.svc
        path: /loki/api/v1/push
        tenant_id: whizard-events-ks
        out_of_order_action: accept
        encoding:
          codec: json
        request:
          retry_attempts: 5
        labels: 
          cluster: "{{ .cluster }}"
          event_type: "{{ .type }}"
          kind: "{{ .involvedObject.kind }}"
          namespace: "{{ .involvedObject.namespace }}"
          reported_by: "{{ .reportingComponent }}"
          reason: "{{ .reason }}"